### ISSUE TITLE
Not compatible with WP-CLI 2.x?

### ISSUE THREAD

**Issue by Ipstenu** [danielbachhuber/reinstall-command#1]
-  Installation request for danielbachhuber/reinstall-command dev-master -> satisfiable by danielbachhuber/reinstall-command[dev-master].
    - Conclusion: remove wp-cli/wp-cli 2.0.1
    - danielbachhuber/reinstall-command dev-master requires wp-cli/wp-cli ^1.1.0 -> satisfiable by wp-cli/wp-cli[v1.1.0, v1.2.0, v1.2.1, v1.3.0, v1.4.0, v1.4.1, v1.5.0, v1.5.1].
    - Can only install one of: wp-cli/wp-cli[v2.0.1, v1.1.0].
    - Can only install one of: wp-cli/wp-cli[v2.0.1, v1.2.0].
    - Can only install one of: wp-cli/wp-cli[v2.0.1, v1.2.1].
    - Can only install one of: wp-cli/wp-cli[v2.0.1, v1.3.0].
    - Can only install one of: wp-cli/wp-cli[v2.0.1, v1.4.0].
    - Can only install one of: wp-cli/wp-cli[v2.0.1, v1.4.1].
    - Can only install one of: wp-cli/wp-cli[v2.0.1, v1.5.0].
    - Can only install one of: wp-cli/wp-cli[v2.0.1, v1.5.1].
    - Installation request for wp-cli/wp-cli 2.0.1 -> satisfiable by wp-cli/wp-cli[2.0.1].

**Comment by danielbachhuber** [comment]
@Ipstenu Sorry about that! I'll pick this up in the next day or two.
